-- TODO: this could be supplemented with data from http://unicode.org/cldr/ which includes localised names for all country/language names, date names, and abbreviations, etc. (in XML)
timezones = {}
types={}
types.logins =
{
	"browser",		--1
	"facebook",		--2
}
types.bitmaps =
{["image/jpeg"]="jpg",["image/png"]="png",["image/jp2"]="jp2",["image/gif"]="gif"}
types.vectors =
{["image/svg+xml"]="svg",["application/postscript"]="eps"}
types.content = {
	html = "text/html; charset=UTF-8",
	json = "application/json; charset=UTF-8",
}

-- TODO: move to i18n app settings
terms = {
	-- the following are auto-populated by servers
	languages ={}, -- indexed by language code
	countries ={options={}}, -- index by country_code, options sorted by native name(s); used by tag.Countries
	nationalities ={options={}},
	e164 = dofile"e164.lua", -- telephone prefixes, for a string lookup provides either a string ['33']="fr" (if single country result) or an array ['1']={"us","ca"} (where multiple countries share the prefix)
}
terms.countries.ordered=terms.countries.options

terms.transliteration =
{
{utf8_upper="À", ascii_upper="A", utf8_lower="à", ascii_lower="a"},
{utf8_upper="Á", ascii_upper="A", utf8_lower="á", ascii_lower="a"},
{utf8_upper="Â", ascii_upper="A", utf8_lower="â", ascii_lower="a"},
{utf8_upper="Ã", ascii_upper="A", utf8_lower="ã", ascii_lower="a"},
{utf8_upper="Ä", ascii_upper="A", utf8_lower="ä", ascii_lower="a"},
{utf8_upper="Æ", ascii_upper="AE", utf8_lower="æ", ascii_lower="ae"},
{utf8_upper="Ç", ascii_upper="C", utf8_lower="ç", ascii_lower="c"},
{utf8_upper="È", ascii_upper="E", utf8_lower="è", ascii_lower="e"},
{utf8_upper="É", ascii_upper="E", utf8_lower="é", ascii_lower="e"},
{utf8_upper="Ê", ascii_upper="E", utf8_lower="ê", ascii_lower="e"},
{utf8_upper="Ë", ascii_upper="E", utf8_lower="ë", ascii_lower="e"},
{utf8_upper="Ì", ascii_upper="I", utf8_lower="ì", ascii_lower="i"},
{utf8_upper="Í", ascii_upper="I", utf8_lower="í", ascii_lower="i"},
{utf8_upper="Î", ascii_upper="I", utf8_lower="î", ascii_lower="i"},
{utf8_upper="Ï", ascii_upper="I", utf8_lower="ï", ascii_lower="i"},
{utf8_upper="Ñ", ascii_upper="N", utf8_lower="ñ", ascii_lower="n"},
{utf8_upper="Ń", ascii_upper="N", utf8_lower="ń", ascii_lower="n"},
{utf8_upper="Ò", ascii_upper="O", utf8_lower="ò", ascii_lower="o"},
{utf8_upper="Ó", ascii_upper="O", utf8_lower="ó", ascii_lower="o"},
{utf8_upper="Ô", ascii_upper="O", utf8_lower="ô", ascii_lower="o"},
{utf8_upper="Ö", ascii_upper="O", utf8_lower="ö", ascii_lower="o"},
{utf8_upper="Ø", ascii_upper="O", utf8_lower="ø", ascii_lower="o"},
{utf8_upper="Ō", ascii_upper="O", utf8_lower="õ", ascii_lower="o"},
{utf8_upper="Œ", ascii_upper="OE", utf8_lower="œ", ascii_lower="oe"},
{utf8_upper="Ù", ascii_upper="U", utf8_lower="ù", ascii_lower="u"},
{utf8_upper="Ú", ascii_upper="U", utf8_lower="ú", ascii_lower="u"},
{utf8_upper="Û", ascii_upper="U", utf8_lower="û", ascii_lower="u"},
{utf8_upper="Ü", ascii_upper="U", utf8_lower="ü", ascii_lower="u"},
}
terms.transliteration_upper = {}
for _,term in pairs(terms.transliteration) do terms.transliteration_upper[term.utf8_lower]=term.utf8_upper end
terms.transliteration_lower = {}
for _,term in pairs(terms.transliteration) do terms.transliteration_lower[term.utf8_upper]=term.utf8_lower end

terms.urlsafe = keyed[[abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-]]
terms.urlsafe_encode = {['<']="%3C",['>']="%3E",['\"']="%22"}
terms.urldisplay_encode = {['<']="%3C",['>']="%3E",['\"']="%22",[' ']="-"}
terms.htmlsafe_encode = {['<']="&lt;",['>']="&gt;",}
terms.seperators = keyed[[_=+& @]]
terms.punctuation = keyed[[,;.:()[]{}*%$#!?''""]]
terms.normalise_remove = { [' ']="", ['\"']="", ["\'"]="", ['.']="", ['-']="", ['+']="", ['&']="", ['!']="", ['?']="", [',']="", [';']="", [':']="", ['–']="", ['—']="", [';']="", ['\\']="", ['/']="", }

terms.email_domains = keyed{
	  "aol.com", "att.net", "comcast.net", "facebook.com", "gmail.com", "gmx.com", "googlemail.com",
	  "google.com", "hotmail.com", "hotmail.co.uk", "mac.com", "me.com", "mail.com", "msn.com",
	  "live.com", "sbcglobal.net", "verizon.net", "yahoo.com", "yahoo.co.uk","googlemail.co.uk",

	  "email.com", "fastmail.fm", "games.com", "gmx.net", "hush.com", "hushmail.com", "icloud.com",
	  "iname.com", "inbox.com", "lavabit.com", "love.com", "outlook.com", "pobox.com", "protonmail.com",
	  "rocketmail.com", "safe-mail.net", "wow.com", "ygm.com",
	  "ymail.com", "zoho.com", "yandex.com",

	  "bellsouth.net", "charter.net", "cox.net", "earthlink.net", "juno.com",

	  "btinternet.com", "virginmedia.com", "blueyonder.co.uk", "freeserve.co.uk", "live.co.uk",
	  "ntlworld.com", "o2.co.uk", "orange.net", "sky.com", "talktalk.co.uk", "tiscali.co.uk",
	  "virgin.net", "wanadoo.co.uk", "bt.com",

	  "sina.com", "qq.com", "naver.com", "hanmail.net", "daum.net", "nate.com", "yahoo.co.jp", "yahoo.co.kr", "yahoo.co.id", "yahoo.co.in", "yahoo.com.sg", "yahoo.com.ph",

	  "hotmail.fr", "live.fr", "laposte.net", "yahoo.fr", "wanadoo.fr", "orange.fr", "gmx.fr", "sfr.fr", "neuf.fr", "free.fr", "voila.fr", "club-internet.fr","bluewin.ch",

	  "gmx.de", "hotmail.de", "live.de", "online.de", "t-online.de", "web.de", "yahoo.de",

	  "libero.it", "virgilio.it", "hotmail.it", "aol.it", "tiscali.it", "alice.it", "live.it", "yahoo.it", "email.it", "tin.it", "poste.it", "teletu.it",

	  "mail.ru", "rambler.ru", "yandex.ru", "ya.ru", "list.ru",

	  "hotmail.be", "live.be", "skynet.be", "voo.be", "tvcablenet.be", "telenet.be",

	  "hotmail.com.ar", "live.com.ar", "yahoo.com.ar", "fibertel.com.ar", "speedy.com.ar", "arnet.com.ar",

	  "yahoo.com.mx", "live.com.mx", "hotmail.es", "hotmail.com.mx", "prodigy.net.mx",

	  "yahoo.com.br", "hotmail.com.br", "outlook.com.br", "uol.com.br", "bol.com.br", "terra.com.br", "ig.com.br", "itelefonica.com.br", "r7.com", "zipmail.com.br", "globo.com", "globomail.com", "oi.com.br",

	  "rediffmail.com","planet.nl","hetnet.nl","sympatico.ca","windstream.net","centurytel.net","chello.nl","ziggo.nl", "bigpond.net.au", "live.ca",
 }



-- TODO: date formats, metric/imperial, domain suffixes
--[[ SOURCES:
http://www.xe.com/symbols.php
http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
http://en.wikipedia.org/wiki/Linguistic_issues_concerning_the_euro
https://en.wikipedia.org/wiki/Single_Euro_Payments_Area
https://en.wikipedia.org/wiki/International_Bank_Account_Number
https://en.wikipedia.org/wiki/Language_and_the_euro#Summary
--]]

-- TODO: add telephone formatter functions, will use either generic (match and remove trunk prefix and reformat as int; or custom function)
--[[
function telephone (value,trunk,country)
	local tel ={}
	for digit in string.gmatch(value,"%d") do table.insert(tel,digit) end
	if tel[1]~="+" then
		if tel[1]==prefix then table.remove
	end
	return table.concat(tel)
--]]

-- TODO: use name as a vocabulary
-- NOTE: digitgroup should not be used, instead half-space is preferred

languages = { -- NOTE: each of these must have a corresponding language_code term defining its name
	en = {},
	['en-gb'] = {},
	['en-us'] = {},
	['en-au'] = {},
	['en-ca'] = {},
	es = {},
	pt = {},
	['pt-br'] = {},
	de = {},
	['de-at'] = {},
	fr = {},
	['fr-ca'] = {}, -- canada
	['fr-be'] = {},
	zh = {},
	et = {},
	ja = {},
	ko = {},
	vi = {},
	fa = {},
	tr = {},
	th = {},
	lo = {},
	nl = {},
	da = {},
	no = {},
	sv = {},
	fi = {},
	hu = {},
	el = {},
	he = {rtl=true},
	it = {},
	cz = {},
	dk = {},
	af = {},
	id = {},
	hi = {},
	ca = {}, -- catalan
	lv = {},
	gd = {},
	ro = {},
	lt = {},
	bs = {},
	hr = {},
	sr = {},
	ru = {},
	uk = {}, -- ukranian
	sk = {},
	cs = {},
	pl = {},
	sl = {},
	ga = {},
	ar = {rtl=true},
	mt = {},
	mk = {},
	is = {},
}

-- locale.date = terms.dates.day_month (default) or terms.dates.month_day; provides default date formats; see format.Date in Kit for use of placeholder in format strings
-- locale.dates = {name="format"} -- defines any exceptions to the defaults; the name "all" will define a single format string to be used for all formats
terms.dates = {}
terms.dates.day_month = {
	numeric = "d/m/yy",
	long = "WWW, ddd MMM| yy",
	short = "WW ddd MM| yy",
	abbreviated = "WW d M.|'y",
	compact = "WW ddd M| 'y",
	mini = "W d M| y",
}
terms.dates.month_day = {
	numeric = "d/m/yy",
	long = "WWW, MMM ddd| yy",
	short = "WW MM ddd| yy",
	abbreviated = "WW M. d| 'y",
	compact = "WW ddd M| 'y",
	mini = "W M d| y",
}
terms.decimals = { -- TODO: reference these in countries, languages; support a formatting string for the integer part integer={nil,nil,nil,",",nil,nil,nil,","} would be iterated as long as there are still numerals whilst inserting the corresponding value; NOTE: currencies and other numbers can be treated differently! this will thus be assumed to apply to currencies as other values are likely to be translated in-place
	point={ decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",},
	comma={ decimal=",", digitgroup=".", digitgroup_utf=" ",},
	arabic={ decimal=",", digitgroup=".", decimal_utf="٫", digitgroup_utf="٬",},
}

-- FIXME: use a named number format instead of individually declaring seperators; and add arabic etc https://en.wikipedia.org/wiki/Decimal_separator#Other_numeral_systems
-- TODO: move currency to vocabulary
-- TODO: symbol_local when using the first declared language, else symbol
-- TODO: currency_code is on left in english, right otherwise
-- NOTE: symbol_r and symbol_l are defined dynamically in the scribe
-- TODO: move currency to vocabulary
-- TODO: move currency values into a new table
-- country_code is iso3166_2; cctld may be specified if different e.g. locales.gb.cctld=="uk"
-- currency_code is iso4217
-- NOTE: alternate country codes are defined in scribe/server:InitialiseLocales
-- .timezone is a suggested default only and is replaced with a pointer to the corresponding timezones[name] table, all available timezones within the area covered by a locale are added to the .timezones table, which is indexed by tz name; this is populated by generic.Elevator
-- languages are for usability and indicate those that are widely understood or useful as fallbacks
-- bounds_display are approximative for containing most of the territory on a map; https://boundingbox.klokantech.com/ and use CSV val
locales =
{ currencies = {}; -- TODO: populate currencies with symbols and remove from countries

	{ -- to match inspecific ripe ip addresses
		urn="europe",
		languages={"en","fr","de","es"},
		currency="Euros",
		country_code="eu", flag="🇪🇺",
		iso3166_3="EUE", -- not actually ISO
		bounds_display={-10.9,34.9,37.8,60.6},
		currency_code="EUR",
		symbol=" €", symbolminor="¢", symbol_r=true, decimal=",", digitgroup="", decimal_utf=",", digitgroup_utf=" ",
		date=terms.dates.day_month,
		timezone="Europe/Brussels",
		time=[[?(Hour):?(Min)]],
		country=false,
		},

	{
		urn="usa",
		e164="1", cellmin=10, cellmax=10,
		country_code="us", flag="🇺🇸",
		iso3166_3="USA",
		bounds_display={-124.92,24.78,-66.87,49.45},
		languages={"en-us","en","es"},
		currency="Dollars",
		currency_code="USD",
		symbol="$", symbolminor="¢", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		mmdd=true,
		date=terms.dates.month_day,
		dates={long="WWW |ddd MMM|, yy"},
		time=[[?(hour12):?(Min) ?(ampm)]],
		timezone="America/New_York",
		provinces={
			["Alabama"]={tel={"205","251","256","334","659","938"}},
			["Alaska"]={tel={"907"}},
			["Arizona"]={tel={"480","520","602","623","928"}},
			["Arkansas"]={tel={"479","501","870"}},
						["California"]={tel={"209","213","310","323","341","369","408","415","424","442","510","530","559","562","619","626","627","628","650","657","661","669","707","714","747","760","764","805","818","831","858","909","916","925","935","949","951"}},
			["Colorado"]={tel={"303","719","720","970"}},
			["Connecticut"]={tel={"203","475","860","959"}},
			["Delaware"]={tel={"302"}},
			["District of Columbia"]={tel={"202"}},
			["Florida"]={tel={"239","305","321","352","386","407","561","689","727","754","772","786","813","850","863","904","941","954"}},
			["Georgia"]={tel={"229","404","470","478","678","706","762","770","912"}},
			["Hawaii"]={tel={"808"}},
			["Idaho"]={tel={"208"}},
			["Illinois"]={tel={"217","224","309","312","331","447","464","618","630","708","730","773","779","815","847","872"}},
			["Indiana"]={tel={"219","260","317","574","765","812"}},
			["Iowa"]={tel={"319","515","563","641","712"}},
			["Kansas"]={tel={"316","620","785","913"}},
			["Kentucky"]={tel={"270","364","502","606","859"}},
			["Louisiana"]={tel={"225","318","337","504","985"}},
			["Maine"]={tel={"207"}},
			["Maryland"]={tel={"227","240","301","410","443","667"}},
			["Massachusetts"]={tel={"339","351","413","508","617","774","781","857","978"}},
			["Michigan"]={tel={"231","248","269","313","517","586","616","679","734","810","906","947","989"}},
			["Minnesota"]={tel={"218","320","507","612","651","763","952"}},
			["Mississippi"]={tel={"228","601","662","769"}},
			["Missouri"]={tel={"314","417","557","573","636","660","816","975"}},
			["Montana"]={tel={"406"}},
			["Nebraska"]={tel={"308","402"}},
			["Nevada"]={tel={"702","775"}},
			["New Hampshire"]={tel={"603"}},
			["New Jersey"]={tel={"201","551","609","732","848","856","862","908","973"}},
			["New Mexico"]={tel={"505","575"}},
			["New York"]={tel={"212","315","347","516","518","585","607","631","646","716","718","845","914","917"}},
			["North Carolina"]={tel={"252","336","704","828","910","919","980","984"}},
			["North Dakota"]={tel={"701"}},
			["Ohio"]={tel={"216","234","283","330","380","419","440","513","567","614","740","937"}},
			["Oklahoma"]={tel={"405","580","918"}},
			["Oregon"]={tel={"503","541","971"}},
			["Pennsylvania"]={tel={"215","267","412","445","484","570","610","717","724","814","835","878"}},
			["Rhode Island"]={tel={"401"}},
			["South Carolina"]={tel={"803","843","864"}},
			["South Dakota"]={tel={"605"}},
			["Tennessee"]={tel={"423","615","731","865","901","931"}},
			["Texas"]={tel={"210","214","254","281","325","361","409","430","432","469","512","682","713","737","806","817","830","832","903","915","936","940","956","972","979"}},
			["Utah"]={tel={"385","435","801"}},
			["Vermont"]={tel={"802"}},
			["Virginia"]={tel={"276","434","540","571","703","757","804"}},
			["Washington"]={tel={"206","253","360","425","509","564"}},
			["West Virginia"]={tel={"304","681"}},
			["Wisconsin"]={tel={"262","414","608","715","920"}},
			["Wyoming"]={tel={"307"}}
			}
		},

	{
		urn="uk",
		e164="44", cellprefix="7", cellmin=10, cellmax=10,
		country_code="gb", flag="🇬🇧",
		cctld="uk",
		iso3166_3="GBR",
		bounds_display={-7.81,49.12,1.83,58.67},
		languages={"en-gb","en",},
		currency="Pounds",
		currency_code="GBP", iban={length=22,sepa=true},
		symbol="£", symbolminor="p", decimal=".", digitgroup=",", decimal_utf="·", digitgroup_utf=" ",
		date=terms.dates.day_month,
		dates={numeric="dd/mm/yy"},
		time=[[?(hour12):?(Min) ?(ampm)]],
		timezone="Europe/London",
		},

	{
		urn="canada",
		e164="1", cellmin=10, cellmax=10,
		country_code="ca", flag="🇨🇦",
		iso3166_3="CAN",
		bounds_display={-130.08,41.69,-64.13,57.67},
		languages={"en-ca","en","fr-ca","fr"},
		currency="Dollars",
		currency_code="CAD",
		symbol="$", symbolminor="¢", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(hour12):?(Min) ?(ampm)]],
		date=terms.dates.month_day,
		dates={numeric="yy-mm-dd"},
		variants = {
			fr = { language="fr-ca",
				date=terms.dates.day_month,
				dates={numeric="yy-mm-dd",long="WWW |ddd MMM| yy"},
				timezone="America/Montreal",
				time=[[?(hour) h ?(min)]],
				decimal=",", digitgroup=".",
			},
		},
		timezone="America/Toronto",
		provinces={
			["Alberta"]={tel={"403","587","780","825"}},
			["British Columbia"]={tel={"236","250","604","778"}},
			["Manitoba"]={tel={"204"}},
			["New Brunswick"]={tel={"506"}},
			["Newfoundland and Labrador"]={tel={"709"}},
			["Nova Scotia"]={tel={"902"}},--also "Prince Edward Island"
			["Prince Edward Island"]={tel={}},
			["Ontario"]={tel={"226","289","343","416","519","613","647","705","807","905"}},
			["Quebec"]={tel={"418","438","450","514","581","819"}},
			["Saskatchewan"]={tel={"306"}},
			["Yukon"]={tel={"867"}},--also "Northwest Territories","Nunavut"
			["Northwest Territories"]={tel={}},
			["Nunavut"]={tel={}}
			},
		},

	{
		urn="japan",
		e164="81",
		country_code="jp", flag="🇯🇵",
		iso3166_3="JPN",
		bounds_display={128.18,30.05,147.93,45.91},
		languages={"ja",},
		currency="Yen",
		currency_code="JPY",
		symbol="¥", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		dates={all="yy年|mm月dd日"},
		time=[[?(hour12)時?(Min)分]],
		timezone="Asia/Tokyo",
		},
	{
		urn="china",
		e164="86", cellprefix="1", cellmin=11, cellmax=11,
		country_code="cn", flag="🇨🇳",
		iso3166_3="CHN",
		bounds_display={76.51,17.86,131.52,53.68},
		languages={"zh",},
		currency="Yuan",
		currency_code="CNY",
		symbol="¥", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		dates={all="yy年|m月d日"},
		time=[[?(hour):?(Min)]],
		timezone="Asia/Beijing",
		},
	{
		urn="taiwan",
		e164="886", cellprefix="1", cellmin=11, cellmax=11,
		country_code="tw", flag="🇹🇼",alt_tld="台灣",
		iso3166_3="TWN",
		bounds_display={119.41,21.78,122.11,25.64},
		languages={"zh",},
		currency="dollars",
		currency_code="TWD",
		symbol="NT$", symbol_local="圓", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		dates={all="yy年|m月d日"},
		time=[[?(hour):?(Min)]],
		timezone="Asia/Taipei",
		},
	{
		urn="germany",
		e164="49", cellprefix="1", cellmin=10, cellmax=11,
		country_code="de", flag="🇩🇪",
		iso3166_3="DEU",
		bounds_display={5.89,47.44,15.16,54.87},
		languages={"de",},
		currency="Euro",
		currency_code="EUR", currency_root=false, iban={length=22,sepa=true},
		symbol=" €", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d.m.yy"},
		timezone="Europe/Berlin",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="france",
		e164="33", cellprefix="6", cellmin=9, cellmax=9,
		country_code="fr", flag="🇫🇷",
		iso3166_3="FRA",
		bounds_display={-4.91,42.29,7.2,51.17},
		languages={"fr",},
		currency="euro",
		currency_code="EUR", currency_root=false, iban={length=27,sepa=true},
		symbol=" €", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="dd-mm-yy",long="WWW |ddd MMM| yy"},
		timezone="Europe/Paris",
		time=[[?(hour) h ?(min)]],
		},
	{
		urn="italy",
		e164="39", cellprefix="3", cellmin=10, cellmax=10,
		country_code="it", flag="🇮🇹",
		iso3166_3="ITA",
		bounds_display={6.51,36.6,18.62,47.12},
		languages={"it",},
		currency="euro", symbolminor="¢",
		currency_code="EUR", currency_root=false, iban={length=27,sepa=true},
		symbol=" €", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		timezone="Europe/Rome",
		time=[[?(hour):?(Min)]],
		},
	{
		urn="russia",
		e164="7", cellprefix="9", cellmin=10, cellmax=10,
		country_code="ru", flag="🇷🇺",
		iso3166_3="RUS",
		bounds_display={27.29,41.18,62.15,64.92},
		languages={"ru",},
		currency="Rubles",
		currency_code="RUB",
		symbol="руб", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="dd.mm.yy"},
		timezone="Europe/Moscow",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="spain",
		e164="34", cellprefix="6", cellmin=9, cellmax=9,
		country_code="es", flag="🇪🇸",
		iso3166_3="ESP",
		bounds_display={-9.39,35.96,4.45,43.88},
		languages={"es",},
		currency="euro",
		currency_code="EUR", currency_root=false, iban={length=24,sepa=true},
		symbol="€", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		timezone="Europe/Madrid",
		time=[[?(hour):?(Min)]],
		},
	{
		urn="australia",
		e164="61", cellprefix="4", cellmin=9, cellmax=9,
		country_code="au", flag="🇦🇺",
		iso3166_3="AUS",
		bounds_display={113.17,-43.78,154.25,-10.89},
		languages={"en-au","en",},
		currency="Dollars",
		currency_code="AUD",
		symbol="$", symbolminor="¢", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		timezone="Australia/Sydney",
		time=[[?(hour12):?(Min) ?(ampm)]],
		},
	{
		urn="new-zealand",
		e164="64", cellprefix="2", cellmin=8, cellmax=10,
		country_code="nz", flag="🇳🇿",
		iso3166_3="NZL",
		bounds_display={166.33,-47.39,178.76,-34.0},
		languages={"en-au","en",},
		currency="Dollars",
		currency_code="NZD",
		symbol="$", symbolminor="¢", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		timezone="Pacific/Auckland",
		time=[[?(hour12):?(Min) ?(ampm)]],
		},
	{
		urn="brazil",
		e164="55",
		country_code="br", flag="🇧🇷",
		iso3166_3="BRA",
		bounds_display={-69.66,-34.18,-34.4,3.45},
		languages={"pt-br","pt"},
		currency="Reais",
		currency_code="BRL", iban={length=29},
		symbol="R$", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		timezone="America/Sao_Paulo",
		time=[[?(hour)h?(min)]],
		},
	{
		urn="india",
		e164="91", cellprefix="9", cellmin=10, cellmax=10,
		country_code="in", flag="🇮🇳",
		iso3166_3="IND",
		bounds_display={68.79,7.84,95.28,34.74},
		languages={"hi","en"},
		currency="Rupees",
		currency_code="INR",
		symbol="₹", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		timezone="Asia/Calcutta",
		time=[[?(hour12):?(Min) ?(ampm)]],
		},
	{
		urn="sri-lanka",
		e164="94",
		country_code="lk", flag="🇱🇰",
		iso3166_3="LKA",
		bounds_display={79.4,5.82,82.07,9.92},
		languages={"si","ta","en"},
		currency="Rupees",
		currency_code="LKR",
		symbol="රු", decimal=".", digitgroup="", decimal_utf=".", digitgroup_utf=" ",
		timezone="Asia/Colombo",
		time=[[?(hour12):?(Min) ?(ampm)]],
		},
	{
		urn="mexico",
		e164="52",
		country_code="mx", flag="🇲🇽",
		iso3166_3="MEX",
		bounds_display={-117.42,14.38,-86.33,32.95},
		languages={"es",},
		currency="Pesos",
		currency_code="MXN",
		symbol="₱", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ", -- uses ' for millions
		timezone="America/Mexico_City",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="korea",
		country_code="kr", flag="🇰🇷",
		iso3166_3="KOR",
		bounds_display={125.98,33.17,129.87,38.69},
		languages={"ko",},
		currency="Won",
		currency_code="KRW",
		symbol="₩", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		dates={mumeric="yy년 |mm월 dd일"},
		timezone="Asia/Seoul",
		time=[[?(hour12)시 ?(Min)분]],
		},
	{
		urn="netherlands",
		e164="31", cellprefix="6", cellmin=8, cellmax=8,
		country_code="nl", flag="🇳🇱",
		iso3166_3="NLD",
		bounds_display={3.35,50.7,7.22,53.48},
		languages={"nl","de","fr"},
		currency="euro",
		currency_code="EUR", currency_root=false, iban={length=18,sepa=true},
		symbol="€ ", symbolminor="¢", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d-m-yy"},
		timezone="Europe/Amsterdam",
		time=[[?(hour).?(Min) uur]],
		},
	{
		urn="poland",
		e164="48", cellmin=9, cellmax=9,
		country_code="pl", flag="🇵🇱",
		iso3166_3="POL",
		bounds_display={14.12,48.96,24.08,54.85},
		languages={"pl",},
		currency="Zlotych",
		currency_code="PLN", iban={length=28,sepa=true},
		symbol="zł", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d.m.yy"},
		timezone="Europe/Warsaw",
		time=[[?(Hour).?(Min)]],
		},
	{
		urn="indonesia",
		e164="62",
		country_code="id", flag="🇮🇩",
		iso3166_3="IDN",
		bounds_display={95.14,-11.03,124.55,5.92},
		languages={"id",},
		currency="Rupiahs",
		currency_code="IDR",
		symbol="Rp", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		timezone="Asia/Jakarta",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="belgium",
		e164="32", cellprefix="4", cellmin=9, cellmax=9,
		country_code="be", flag="🇧🇪",
		iso3166_3="BEL",
		bounds_display={2.51,49.51,6.41,51.52},
		languages={"nl","fr-be","fr","de"},
		currency="euro",
		currency_code="EUR", currency_root=false, iban={length=16,sepa=true},
		symbol=" €", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		timezone="Europe/Brussels",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="switzerland",
		e164="41", cellprefix="7", cellmin=9, cellmax=9, -- cellprefix technically excludes 71
		country_code="ch", flag="🇨🇭",
		iso3166_3="CHE",
		bounds_display={5.91,45.78,10.52,47.8},
		languages={"de","fr","it"},
		currency="Francs",
		currency_code="CHF", iban={length=21,sepa=true},
		symbol="fr.", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ", -- TODO: in german symbol is capitalised Fr.
		dates={numeric="d-m-yy"},
		timezone="Europe/Zurich",
		time=[[?(Hour):?(Min)]],
	},
	{
		urn="luxembourg",
		e164="352", cellprefix="6", cellmin=9, cellmax=9,
		country_code="lu", flag="🇱🇺",
		iso3166_3="LUX",
		bounds_display={}, -- TODO:
		languages={"lb","fr","de"},
		currency="Francs",
		currency_code="EUR", iban={}, -- TODO:
		symbol=" €", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d-m-yy"},
		timezone="Europe/Luxembourg",
		time=[[?(Hour):?(Min)]],
	},
	{
		urn="sweden",
		e164="46", cellprefix="7",
		country_code="se", flag="🇸🇪",
		iso3166_3="SWE",
		bounds_display={10.93,55.34,24.12,68.03},
		languages={"sv","no","da","fi","de"},
		currency="Kronor",
		currency_code="SEK", iban={length=24,sepa=true},
		symbol="kr", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d/m-yy"},
		timezone="Europe/Stockholm",
		timeseperator=".",
		time=[[?(Hour):?(Min)]],
	},
	{
		urn="saudi-arabia",
		e164="966",
		country_code="sa", flag="🇸🇦",
		iso3166_3="SAU",
		bounds_display={34.55,16.41,52.26,31.47},
		languages={"ar",},
		currency="Riyals",
		currency_code="SAR", iban={length=24},
		symbol="﷼", symbol_r=true, decimal_utf="٫",
		time=[[?(Hour12):?(Min) ?(ampm)]],
		timezone="Asia/Riyadh",
		},
	{
		urn="south-africa",
		e164="27",
		country_code="za", flag="🇿🇦",
		iso3166_3="ZAF",
		bounds_display={16.57,-34.97,32.9,-22.11},
		languages={"af","en","nl"},
		currency="Rand",
		currency_code="ZAR",
		symbol="R", decimal_utf="٫",
		timezone="Africa/Johannesburg",
		time=[[?(hour):?(Min) ?(ampm)]],
		},
	{
		urn="norway",
		e164="47", cellmin=8, cellmax=8,
		country_code="no", flag="🇳🇴",
		iso3166_3="NOR",
		bounds_display={4.58,57.92,30.93,70.78},
		languages={"no","sv","fi","da"},
		currency="Kroner",
		currency_code="NOK", iban={length=15,sepa=true},
		symbol="kr", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d-m-yy"},
		timezone="Europe/Oslo",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="austria",
		e164="43", cellprefix="6",
		country_code="at", flag="🇦🇹",
		iso3166_3="AUT",
		bounds_display={9.5,46.35,17.2,48.95},
		languages={"de-at","de",},
		currency="Euro",
		currency_code="EUR", currency_root=false, iban={length=20,sepa=true},
		symbol=" €", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d-m-yy"},
		timezone="Europe/Vienna",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="denmark",
		e164="45", cellmin=8, cellmax=8,
		country_code="dk", flag="🇩🇰",
		iso3166_3="DNK",
		bounds_display={7.99,54.77,12.75,57.64},
		languages={"da","sv"},
		currency="Kroner",
		currency_code="DKK", iban={length=18,sepa=true},
		symbol="kr", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d-m-yy"},
		timezone="Europe/Copenhagen",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="finland",
		e164="358", cellmin=9, cellmax=9,
		country_code="fi", flag="🇫🇮",
		iso3166_3="FIN",
		bounds_display={19.41,59.74,31.7,67.66},
		languages={"fi","sv","no","da","de"},
		currency="euro",
		currency_code="EUR", currency_root=false, iban={length=18,sepa=true},
		symbol=" €", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		dates={numeric="d.m.yy"},
		timezone="Europe/Helsinki",
		time=[[?(hour).?(Min)]],
		},
	{
		urn="ireland",
		e164="353", cellprefix="8",
		country_code="ie", flag="🇮🇪",
		iso3166_3="IRL",
		bounds_display={-10.53,51.4,-5.42,55.27},
		languages={"en","ga",},
		currency="euro",
		currency_code="EUR", currency_root=false, iban={length=22,sepa=true},
		symbol="€", symbolminor="¢", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		dates={numeric="d-m-yy"},
		timezone="Europe/Dublin",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="uae",
		e164="971", cellprefix="5",
		country_code="ae", flag="🇦🇪",
		iso3166_3="ARE",
		bounds_display={51.57,22.88,56.43,26.08},
		languages={"ar",},
		currency="Dirhams",
		currency_code="AED", iban={length=23},
		symbol="د.إ", decimal=".", decimal_utf="٫", digitgroup=",", digitgroup_utf="٬",
		timezone="Asia/Dubai",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="portugal",
		e164="351", cellprefix="9", cellmin=9, cellmax=9,
		country_code="pt", flag="🇵🇹",
		iso3166_3="PRT",
		bounds_display={-9.55,36.92,-6.18,42.17},
		languages={"pt","es"},
		currency="euro",
		currency_code="EUR", currency_root=false, iban={length=25,sepa=true},
		symbol="€", symbolminor="¢", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		timezone="Europe/Lisbon",
		time=[[?(Hour):?(Min)]],
		},
	{
		urn="hong-kong",
		e164="852", cellmin=8, cellmax=8,
		country_code="hk", flag="🇭🇰", alt_tld="香港",
		iso3166_3="HKG",
		bounds_display={113.84,22.18,114.41,22.54},
		languages={"zh","en"},
		currency_code="HKD",
		symbol="元", symbolminor="仙", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		dates={all="yy年|m月d日"},
		time=[[?(Hour12):?(Min) ?(ampm)]],
		timezone="Asia/Hong_Kong",
		},
	{
		urn="singapore",
		e164="65", cellmin=8, cellmax=8,
		country_code="sg", flag="🇸🇬",
		iso3166_3="SGP",
		bounds_display={103.589,1.193,104.089,1.488},
		languages={"en","zh"},
		currency="Dollars",
		currency_code="SGD",
		symbol="$", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		dates={all="yy年|m月d日"},
		time=[[?(Hour12):?(Min) ?(ampm)]],
		timezone="Asia/Singapore",
		},
	{
		urn="malaysia",
		e164="60",cellprefix="1",cellmin=9,cellmax=10,
		country_code="my", flag="🇲🇾",
		iso3166_3="MYS",
		bounds_display={100.06,0.95,118.7,7.04},
		languages={"en","zsm"},
		currency="ringgit",
		currency_code="MYR",
		symbol="RM", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(Hour12):?(Min) ?(ampm)]],
		timezone="Asia/Kuala_Lumpur",
		},
	{
		urn="georgia",
		e164="995", cellmin=12, cellmax=12,
		country_code="ge", flag="🇬🇪",
		iso3166_3="GEO",
		bounds_display={39.99,41.13,46.42,43.58},
		languages={"ka","ab","ru"},
		currency="lari",
		currency_code="GEL",
		symbol="₾", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Tiblisi",
		},
	{
		urn="armenia",
		e164="374",
		country_code="am", flag="🇦🇲",
		iso3166_3="ARM",
		bounds_display={43.44,38.83,46.65,41.32},
		languages={"hy",},
		currency="դրամ",
		currency_code="AMD",
		symbol="֏", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Yerevan",
		},
	{
		urn="greece",
		e164="30",
		country_code="gr", flag="🇬🇷",
		iso3166_3="GRC",
		bounds_display={19.32,34.78,28.33,41.58},
		languages={"el",},
		currency="euro",
		currency_code="EUR",currency_root=false,
		symbol="€", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Athens",
		},
	{
		urn="malta",
		e164="356",
		country_code="mt", flag="🇲🇹",
		iso3166_3="MLT",
		bounds_display={14.16,35.79,14.59,36.08},
		languages={"mt","en","it"},
		currency="euro",
		currency_code="EUR",currency_root=false,
		symbol="€", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Valetta",
		},
	{
		urn="bulgaria",
		e164="359",
		country_code="bg", flag="🇧🇬",
		iso3166_3="BGR",
		bounds_display={22.37,41.29,28.65,44.21},
		languages={"bg",},
		currency="лев",
		currency_code="BGN",
		decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Sofia",
		},
	{
		urn="hungary",
		e164="36",
		country_code="hu", flag="🇭🇺",
		iso3166_3="HUN",
		bounds_display={16.18,45.74,22.86,48.55},
		languages={"hu",},
		currency="forint",symbol=" Ft",symbol_r=true,
		currency_code="HUF",
		decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Budapest",
		},
	{
		urn="egypt",
		e164="20", cellprefix="1", cellmin=10, cellmax=10,
		country_code="eg", flag="🇪🇬",
		iso3166_3="EGY",
		bounds_display={24.84,21.9,36.94,31.76},
		languages={"ar",},
		currency="pounds",
		currency_code="EGP",
		symbol="ج.م", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Africa/Cairo",
		},
	{
		urn="morocco",
		e164="212", cellprefix="6", cellmin=9, cellmax=9,
		country_code="ma", flag="🇲🇦",
		iso3166_3="MAR",
		bounds_display={-11.78,27.65,-1.39,35.96},
		languages={"ar","fr"},
		currency="dirhams",
		currency_code="MAD",
		symbol="DH", decimal=",", digitgroup=".",
		time=[[?(Hour):?(Min)]],
		timezone="Africa/Rabat",
		},
	{
		urn="tunisia",
		e164="216",
		country_code="tn", flag="🇹🇳",
		iso3166_3="TUN",
		bounds_display={7.52,30.13,11.69,37.63},
		languages={"ar","fr"},
		currency="dinar",
		currency_code="TND",
		symbol="DT", decimal=",", digitgroup=".",
		time=[[?(Hour):?(Min)]],
		timezone="Africa/Tunis",
		},
	{
		urn="colombia",
		e164="212", cellprefix="6", cellmin=9, cellmax=9,
		country_code="co", flag="🇨🇴",
		iso3166_3="COL",
		bounds_display={-79.02,-2.56,-67.34,12.58},
		languages={"es"},
		currency="peso",
		currency_code="COP",
		symbol="$", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Bogota",
		},
	{
		urn="venezuela",
		e164="58",
		country_code="ve", flag="🇻🇪",
		iso3166_3="VEN",
		bounds_display={-72.99,1.72,-60.26,12.26},
		languages={"es"},
		currency="bolívar",
		currency_code="VEB",
		symbol="Bs.", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Caracas",
		},
	{
		urn="serbia",
		e164="381", cellprefix="6", cellmin=9, cellmax=9,
		country_code="rs", flag="🇭🇷",
		iso3166_3="SRB",
		bounds_display={18.82,42.21,23.03,46.19},
		languages={"sr","ru","hu"},
		currency="dinars",
		currency_code="RSD",
		symbol="дин", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Belgrade",
		},
	{
		urn="montenegro",
		e164="382", cellprefix="", cellmin=8, cellmax=12,
		country_code="me", flag="🇲🇪",
		iso3166_3="MNE",
		bounds_display={18.4,41.83,20.36,43.56},
		languages={"sr","bs","ru"},
		currency_code="EUR",currency_root=false,
		symbol="€", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Podgorica",
		},
	{
		urn="croatia",
		e164="385", cellprefix="9", cellmin=9, cellmax=9,
		country_code="hr", flag="🇭🇷",
		iso3166_3="HRV",
		bounds_display={13.45,42.4,19.45,46.57},
		languages={"hr"},
		currency_code="HRK",
		symbol="kn", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Zagreb",
		},
	{
		urn="cyprus",
		e164="357",
		country_code="cy", flag="🇨🇾",
		iso3166_3="CYP",
		bounds_display={32.22,34.52,34.62,35.71},
		languages={"el","tr"},
		currency="euro",
		currency_code="EUR",currency_root=false,
		symbol="€", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Asia/Nicosia",
		},
	{
		urn="romania",
		e164="40", cellprefix={"7","6"}, cellmin=8, cellmax=9,
		country_code="ro", flag="🇷🇴",
		iso3166_3="ROU",
		bounds_display={20.26,43.65,29.75,48.28},
		languages={"ro"},
		currency="lei",
		currency_code="RON",
		decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Bucharest",
		},
	{
		urn="estonia",
		e164="372", cellprefix={"5","8"}, cellmin=8, cellmax=12,
		country_code="ee", flag="🇪🇪",
		iso3166_3="EST",
		bounds_display={21.94,57.55,28.24,59.66},
		languages={"et","fi","ru"},
		currency_code="EUR",currency_root=false,
		symbol="€", symbolminor="¢", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Tallinn",
		},
	{
		urn="lithuania",
		e164="370", cellprefix={"8",}, cellmin=8, cellmax=8,
		country_code="lt", flag="🇱🇹",
		iso3166_3="LTU",
		bounds_display={20.92,53.91,26.8,56.42},
		languages={"lt","lv","ru"},
		currency_code="EUR",currency_root=false,
		symbol="€", symbolminor="¢", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Vilnius",
		},
	{
		urn="ukraine",
		e164="380",
		country_code="ua", alt_tld="укр", flag="🇺🇦",
		iso3166_3="UKR",
		bounds_display={22.13,44.34,39.99,52.36},
		languages={"uk","ru"},
		currency_code="UAH",currency="гривня",
		symbol="₴", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Kyiv",
		},
	{
		urn="russia",
		e164="7", cellprefix={"9",},
		country_code="ru", alt_tld="рф", flag="🇷🇺",
		iso3166_3="RUS",
		bounds_display={27.55,41.5,69.58,64.85},
		languages={"ru"},
		currency_code="RUB",currency="рубль",
		symbol="₽", symbol_r=true, decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Europe/Moscow",
		},
	{
		urn="thailand",
		e164="66", cellprefix={"5","8"}, cellmin=8, cellmax=12,
		country_code="th", flag="🇹🇭",
		iso3166_3="THA",
		bounds_display={97.47,5.7,105.54,20.49},
		languages={"th",},
		currency_code="THB",
		currency="baht",
		symbol="฿",  decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Asia/Bangkok",
		},
	{
		urn="cambodia",
		e164="855", cellprefix={"5","8"}, cellmin=8, cellmax=12,
		country_code="kh", flag="🇰🇭",
		iso3166_3="KHM",
		bounds_display={102.35,10.39,107.51,14.59},
		languages={"km",},
		currency_code="KHR",
		currency="riel",
		symbol="៛",  decimal=".", digitgroup="", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Asia/Phnom_Penh",
		},
	{
		urn="ecuador",
		e164="593", cellprefix="9", cellmin=10, cellmax=10,
		country_code="ec", flag="🇪🇨",
		iso3166_3="ECA",
		bounds_display={-81.05,-4.97,-75.2,1.46},
		languages={"es",},
		currency_code="USD",
		currency="dollars",
		symbol="$", symbolminor="¢", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Guayaquil",
		},
	{
		urn="belize",
		e164="501", cellprefix={"6","7"}, cellmin=7, cellmax=7,
		country_code="bz", flag="🇧🇿",
		iso3166_3="BLZ",
		bounds_display={-89.24,15.91,-87.88,18.45},
		languages={"en",},
		currency_code="BZD",
		currency="dollars",
		symbol="BZ$", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Belize",
		},
	{
		urn="tanzania",
		e164="255", cellprefix={"6","7"}, cellmin=7, cellmax=7,
		country_code="tz", flag="🇹🇿",
		iso3166_3="TZA",
		bounds_display={29.5,-11.57,40.49,-1.01},
		languages={"en",},
		currency_code="TZS",
		currency="shilingi",
		symbol="TSh", symbolminor="/", decimal=".", digitgroup="", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Africa/Dar_es_Salaam",
		},
	{
		urn="ivory-coast",
		e164="225", cellmin=8, cellmax=10,
		country_code="ci", flag="🇨🇮",
		iso3166_3="CIV",
		bounds_display={-8.57,4.28,-2.4,10.61},
		languages={"fr",},
		currency_code="XOF",
		currency="francs",
		symbol="CFA", symbolminor="c", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Africa/Abidjan",
		},
	{
		urn="philippines",
		e164="63", cellprefix="9", cellmin=10, cellmax=10,
		country_code="ph", flag="🇵🇭",
		iso3166_3="PHL",
		bounds_display={116.72,4.61,126.8,20.84},
		languages={"fil","en","es"},
		currency_code="PHP",
		currency="pesos",
		symbol="₱", symbolminor="¢", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Asia/Manila",
		},
	{
		urn="costa-rica",
		e164="506", cellprefix={"5","6","7","8"}, cellmin=8, cellmax=8,
		country_code="cr", flag="🇨🇷",
		iso3166_3="CRI",
		bounds_display={-85.91,8.16,-82.58,11.22},
		languages={"es"},
		currency_code="CRC",
		currency="colónes",
		symbol="₡", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Costa_Rica",
		},
	{
		urn="panama",
		e164="507",
		country_code="pa", flag="🇵🇦",
		iso3166_3="PAN",
		bounds_display={-83.0,7.18,-77.26,9.69},
		languages={"es"},
		currency_code="USD",
		currency="dollars",
		symbol="$", symbolminor="¢", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Panama",
		},
	{
		urn="nicaragua",
		e164="505", cellmin=8, cellmax=8,
		country_code="ni", flag="🇳🇮",
		iso3166_3="NIC",
		bounds_display={-87.7,10.74,-82.91,15.0},
		languages={"es","en",},
		currency_code="NIO",
		currency="córdoba",
		symbol="C$", decimal=".", digitgroup=",", decimal_utf=".", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Managua",
		},
	{
		urn="vietnam",
		e164="84", cellprefix={"3","5","9","7","8"}, cellmin=10, cellmax=10,
		country_code="vn", flag="🇻🇳",
		iso3166_3="VNM",
		bounds_display={102.18,8.54,109.57,23.06},
		languages={"vi",},
		currency_code="VND",
		currency="đồng",
		symbol="₫", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Asia/Ho_Chi_Minh",
		},
	{
		urn="argentina",
		e164="54",
		country_code="ar", flag="🇦🇷",
		iso3166_3="ARG",
		bounds_display={-73.46,-52.28,-56.52,-21.93},
		languages={"es"},
		currency_code="ARS",
		currency="peso",
		symbol="$", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Buenos_Aires",
		},
	{
		urn="uruguay",
		e164="598",
		country_code="uy", flag="🇺🇾",
		iso3166_3="URY",
		bounds_display={-58.51,-35.0,-53.12,-30.09},
		languages={"es"},
		currency_code="UYU",
		currency="peso",
		symbol="$U", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="America/Montevideo",
		},
	{
		urn="namibia",
		e164="264",
		country_code="na", flag="🇳🇦",
		iso3166_3="NAM",
		bounds_display={11.53,28.97,25.26,-16.96},
		languages={"en","af"},
		currency_code="NAD",
		currency="dollar",
		symbol="N$", decimal=",", digitgroup=".", decimal_utf=",", digitgroup_utf=" ",
		time=[[?(Hour):?(Min)]],
		timezone="Africa/Windhoek",
		},
}
