en.captcha_question = "Answer the sum:"
de.captcha_question = "Beantworten sie die summe:"
fr.captcha_question = "Réponse à la somme:"
en.this_is_wrong = "that was wrong"
de.this_is_wrong = "das war falsch"
fr.this_is_wrong = "ce qui n'allait pas"
en.additem = "add item"
fr.additem = "ajouter un article"
de.additem = "neues element hinzufügen"
en.noitems = "no items"
fr.noitems = "pas d'articles"
de.noitems = "keine artikel"
en.removeitem = "remove this item"
fr.removeitem = "supprimer cet article"
de.removeitem = "diesen artikel entfernen"
en.specifycountry = "type country name or code"

en.midnight = "midnight"
fr.midnight = "minuit"
de.midnight = "Mitternacht"
ko.midnight = "자정"
en.noon = "noon"
fr.noon = "midi"
de.noon = "Mittag"
ko.noon = "정오"

en.country_			="" -- only needed if a value="" item is used with tag.Countries; handlign logic should generally strip this from usage
